install: #при первом клонировании репозитория
npm ci
brain-games: #руками довольно долго, а make brain-games быстро и просто
node bin/brain-games.js 
publish: # 
npm publish --dry-runДля отладки публикации не нужно добавлять пакет в основной каталог NPM. На протяжении всего проекта используйте аргумент --dry-run 

